variable "api_versions_file" {
  type        = string
  default     = "api_versions.json"
  description = "The filename of the JSON file containing Azure Resource Providers and their latest stable API versions. This file will be generated by the download_api_versions.sh script."
}

variable "type" {
  type        = string
  description = "The type of the resource to query. This should be in the format 'Provider/ResourceType'."
}

variable "parent_id" {
  type        = string
  default     = ""
  description = "The parent ID under which to query for resources. This should be in the format '/subscriptions/{subscriptionId}' or '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}'."
  validation {
    condition     = var.parent_id == "" || can(regex("(?i)^(/subscriptions/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}(/resourceGroups/[^/]+)?|/providers/[^/]+(/[^/]+)+)(/providers/[^/]+(/[^/]+){1,})?$", var.parent_id))
    error_message = "parent_id must be a valid Azure resource ID for a subscription or resource group."
  }
}

variable "name" {
  type        = string
  description = "The name value to filter resources by."
  default     = ""
}

variable "tags" {
  type        = map(string)
  description = "A map of tag key/value pairs to filter resources by. Only resources that have all specified tags with the given values will be returned."
  default     = {}
}

variable "location" {
  type        = string
  description = "The location value to filter resources by."
  default     = ""
}

variable "return_attributes" {
  type        = list(string)
  description = "The list of attributes to return for each resource. This should be a list of valid resource properties (e.g. ['id', 'name', 'location']). If empty, all attributes will be returned."
  default     = []
}
